# general plugins (managers, colorscheme etc.)
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
    syntax enable
    set background=dark
    colorscheme iceberg
    " enable 24-bit color
    set termguicolors
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {
        \ 'colorscheme': 'iceberg',
        \ }
'''

[[plugins]]
repo = 'maximbaz/lightline-ale'
depends = ['dense-analysis/ale', 'itchyny/lightline.vim']

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git', 'defx-icons']
hook_add = '''
    source ~/.config/nvim/.plugged/defx.rc.vim
'''

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
hook_add = '''
    source ~/.config/nvim/.plugged/lsp_config.rc.vim
'''

[[plugins]]
repo = 'hrsh7th/nvim-cmp'
hook_add = '''
    source ~/.config/nvim/.plugged/cmp.rc.vim
'''

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'

[[plugins]]
repo = 'hrsh7th/cmp-buffer'

[[plugins]]
repo = 'hrsh7th/cmp-cmdline'

[[plugins]]
repo = 'L3MON4D3/LuaSnip'

[[plugins]]
repo = 'onsails/lspkind-nvim'
hook_add = '''
    source ~/.config/nvim/.plugged/lspkind.rc.lua
'''

[[plugins]]
repo = 'simrat39/rust-tools.nvim'

[[plugins]]
repo = 'windwp/nvim-autopairs'
hook_add = '''
    source ~/.config/nvim/.plugged/autopairs.rc.lua
'''

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
hook_add = '''
    let g:loaded_telescope = 1
    source ~/.config/nvim/.plugged/telescope.rc.vim
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
hook_add = '''
    let g:loaded_nvim_treesitter = 1
    source ~/.config/nvim/.plugged/treesitter.rc.vim
'''
hook_post_update = '''
    TSUpdate
'''
